# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T00:43:12+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class GoogleCloudAdvisorynotificationsV1CsvCsvRow(BaseModel):
    entries: Optional[List[str]] = Field(
        None,
        description='The data entries in a CSV file row, as a string array rather than a single comma-separated string.',
    )


class NotificationType(Enum):
    NOTIFICATION_TYPE_UNSPECIFIED = 'NOTIFICATION_TYPE_UNSPECIFIED'
    NOTIFICATION_TYPE_SECURITY_PRIVACY_ADVISORY = (
        'NOTIFICATION_TYPE_SECURITY_PRIVACY_ADVISORY'
    )
    NOTIFICATION_TYPE_SENSITIVE_ACTIONS = 'NOTIFICATION_TYPE_SENSITIVE_ACTIONS'


class LocalizationState(Enum):
    LOCALIZATION_STATE_UNSPECIFIED = 'LOCALIZATION_STATE_UNSPECIFIED'
    LOCALIZATION_STATE_NOT_APPLICABLE = 'LOCALIZATION_STATE_NOT_APPLICABLE'
    LOCALIZATION_STATE_PENDING = 'LOCALIZATION_STATE_PENDING'
    LOCALIZATION_STATE_COMPLETED = 'LOCALIZATION_STATE_COMPLETED'


class GoogleCloudAdvisorynotificationsV1Text(BaseModel):
    enText: Optional[str] = Field(None, description='The English copy.')
    localizationState: Optional[LocalizationState] = Field(
        None, description='Status of the localization.'
    )
    localizedText: Optional[str] = Field(
        None, description='The requested localized copy (if applicable).'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class View(Enum):
    NOTIFICATION_VIEW_UNSPECIFIED = 'NOTIFICATION_VIEW_UNSPECIFIED'
    BASIC = 'BASIC'
    FULL = 'FULL'


class GoogleCloudAdvisorynotificationsV1Csv(BaseModel):
    dataRows: Optional[List[GoogleCloudAdvisorynotificationsV1CsvCsvRow]] = Field(
        None,
        description='The list of data rows in a CSV file, as string arrays rather than as a single comma-separated string.',
    )
    headers: Optional[List[str]] = Field(
        None, description='The list of headers for data columns in a CSV file.'
    )


class GoogleCloudAdvisorynotificationsV1MessageBody(BaseModel):
    text: Optional[GoogleCloudAdvisorynotificationsV1Text] = Field(
        None, description='The text content of the message body.'
    )


class GoogleCloudAdvisorynotificationsV1Subject(BaseModel):
    text: Optional[GoogleCloudAdvisorynotificationsV1Text] = Field(
        None, description='The text content.'
    )


class GoogleCloudAdvisorynotificationsV1Attachment(BaseModel):
    csv: Optional[GoogleCloudAdvisorynotificationsV1Csv] = Field(
        None, description='A CSV file attachment. Max size is 10 MB.'
    )
    displayName: Optional[str] = Field(None, description='The title of the attachment.')


class GoogleCloudAdvisorynotificationsV1Message(BaseModel):
    attachments: Optional[List[GoogleCloudAdvisorynotificationsV1Attachment]] = Field(
        None, description='The attachments to download.'
    )
    body: Optional[GoogleCloudAdvisorynotificationsV1MessageBody] = Field(
        None, description='The message content.'
    )
    createTime: Optional[str] = Field(
        None, description='The Message creation timestamp.'
    )
    localizationTime: Optional[str] = Field(
        None, description='Time when Message was localized'
    )


class GoogleCloudAdvisorynotificationsV1Notification(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. Time the notification was created.'
    )
    messages: Optional[List[GoogleCloudAdvisorynotificationsV1Message]] = Field(
        None, description='A list of messages in the notification.'
    )
    name: Optional[str] = Field(
        None,
        description='The resource name of the notification. Format: organizations/{organization}/locations/{location}/notifications/{notification}.',
    )
    notificationType: Optional[NotificationType] = Field(
        None, description='Type of notification'
    )
    subject: Optional[GoogleCloudAdvisorynotificationsV1Subject] = Field(
        None, description='The subject line of the notification.'
    )


class GoogleCloudAdvisorynotificationsV1ListNotificationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
    notifications: Optional[List[GoogleCloudAdvisorynotificationsV1Notification]] = (
        Field(None, description='List of notifications under a given parent.')
    )
    totalSize: Optional[int] = Field(
        None, description='Estimation of a total number of notifications.'
    )
